name: Maintain & Deploy (Fr)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  maintenance:
    uses: ./.github/workflows/maintenance.tpl.yml
    with:
      BRANCH: main
      CLEAN: false
      UPDATE_REQUIREMENTS: true
      OPTIMIZE_IMAGES: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
      AUTHOR_EMAIL: ${{ secrets.author_email || 'github-actions[bot]@users.noreply.github.com' }}
      AUTHOR_NAME: ${{ secrets.author_name || 'github-actions[bot]' }}
  deploy:
    needs: maintenance
    if: ${{ success() }}
    uses: ./.github/workflows/deploy.yml
    with:
      FETCH_SUBMODULE: false #change this if you use submodules
    secrets:
      GH_PAT: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
